### ISSUE TITLE
index out of range in convert_aa_response_to_models

### ISSUE THREAD

**Issue by ldwnt** [xmsley614/nt_tool#11]
use_aa.py
search for HKG to DXB on 2023-05-20 @ 14:56:56
error
Traceback (most recent call last):
  File "D:\python\nt_tool\use_aa.py", line 37, in <module>
    v1 = convert_aa_response_to_models(response)
  File "D:\python\nt_tool\nt_parser.py", line 262, in convert_aa_response_to_models
    is_mix, mix_detail = calculate_aa_mix_by_segment(CabinClass(temp_pricing.cabin_class), duration_list,
  File "D:\python\nt_tool\nt_parser.py", line 75, in calculate_aa_mix_by_segment
    mix_detail = '+'.join(str(round(percentage_list[x] * 100, 0)) + '%' + actual_cabin_list[x]
  File "D:\python\nt_tool\nt_parser.py", line 75, in <genexpr>
    mix_detail = '+'.join(str(round(percentage_list[x] * 100, 0)) + '%' + actual_cabin_list[x]
IndexError: list index out of range

**Comment by xmsley614** [comment]
Thanks for issue. The bug has been located and will be fixed next update.
